-- Expanded Search Synonyms Seed
-- Maps: tools/products → services, problems → providers, brands → categories,
-- Hindi/Urdu/Arabic colloquial → English canonical, common misspellings

INSERT INTO search_synonyms (term, canonical_term, language) VALUES

-- ═══════════════════════════════════════════════════════
-- CONSTRUCTION & TOOLS
-- ═══════════════════════════════════════════════════════
('hammer', 'construction tools', 'en'),
('sledge', 'demolition tools', 'en'),
('sledgehammer', 'demolition tools', 'en'),
('wrench', 'plumbing tools', 'en'),
('drill', 'power tools', 'en'),
('screwdriver', 'hardware tools', 'en'),
('saw', 'carpentry tools', 'en'),
('cement', 'construction materials', 'en'),
('brick', 'construction materials', 'en'),
('sand', 'construction materials', 'en'),
('gravel', 'construction materials', 'en'),
('tiles', 'flooring', 'en'),
('marble', 'flooring', 'en'),
('granite', 'countertops', 'en'),
('paint brush', 'painting', 'en'),
('roller', 'painting', 'en'),
('putty', 'wall finishing', 'en'),
('primer', 'painting', 'en'),
('ladder', 'construction equipment', 'en'),
('scaffolding', 'construction equipment', 'en'),
('rebar', 'construction materials', 'en'),
('concrete', 'construction materials', 'en'),
('plywood', 'wood', 'en'),
('drywall', 'wall finishing', 'en'),
('roofing', 'roof repair', 'en'),
('waterproofing', 'construction services', 'en'),
('saria', 'construction materials', 'ur'),
('bajri', 'construction materials', 'ur'),
('reti', 'sand', 'ur'),
('eent', 'brick', 'ur'),

-- ═══════════════════════════════════════════════════════
-- PLUMBING
-- ═══════════════════════════════════════════════════════
('leaking tap', 'plumber', 'en'),
('leaky faucet', 'plumber', 'en'),
('clogged drain', 'plumber', 'en'),
('blocked pipe', 'plumber', 'en'),
('toilet repair', 'plumber', 'en'),
('water heater', 'plumber', 'en'),
('geyser repair', 'plumber', 'en'),
('pipeline', 'plumber', 'en'),
('water tank', 'plumber', 'en'),
('tap fitting', 'plumber', 'en'),
('bathroom fitting', 'plumber', 'en'),
('flush repair', 'plumber', 'en'),
('sewer', 'plumber', 'en'),
('drainage', 'plumber', 'en'),
('water pump', 'plumber', 'en'),
('motor pump', 'plumber', 'en'),
('nalkay ki marammat', 'plumber', 'ur'),
('toilet band', 'plumber', 'ur'),
('pani ki tanki', 'water tank', 'ur'),

-- ═══════════════════════════════════════════════════════
-- ELECTRICAL
-- ═══════════════════════════════════════════════════════
('short circuit', 'electrician', 'en'),
('power outage', 'electrician', 'en'),
('socket repair', 'electrician', 'en'),
('switch repair', 'electrician', 'en'),
('fan repair', 'electrician', 'en'),
('light fitting', 'electrician', 'en'),
('chandelier', 'electrician', 'en'),
('inverter', 'electrician', 'en'),
('voltage stabilizer', 'electrician', 'en'),
('circuit breaker', 'electrician', 'en'),
('mcb', 'electrician', 'en'),
('wiring repair', 'electrician', 'en'),
('meter installation', 'electrician', 'en'),
('generator', 'electrician', 'en'),
('solar panel', 'solar installation', 'en'),
('led lights', 'lighting', 'en'),
('pankha', 'fan repair', 'ur'),
('bulb', 'electrician', 'en'),
('tubelight', 'electrician', 'en'),

-- ═══════════════════════════════════════════════════════
-- MOBILE & ELECTRONICS
-- ═══════════════════════════════════════════════════════
('broken screen', 'mobile repair', 'en'),
('cracked screen', 'mobile repair', 'en'),
('battery replacement', 'mobile repair', 'en'),
('charging port', 'mobile repair', 'en'),
('iphone', 'mobile repair', 'en'),
('samsung', 'mobile repair', 'en'),
('xiaomi', 'mobile repair', 'en'),
('oppo', 'mobile repair', 'en'),
('vivo', 'mobile repair', 'en'),
('realme', 'mobile repair', 'en'),
('laptop repair', 'computer repair', 'en'),
('computer repair', 'computer repair', 'en'),
('printer repair', 'computer repair', 'en'),
('wifi setup', 'networking', 'en'),
('router', 'networking', 'en'),
('cctv', 'security systems', 'en'),
('camera installation', 'security systems', 'en'),
('intercom', 'security systems', 'en'),
('tv repair', 'electronics repair', 'en'),
('lcd repair', 'electronics repair', 'en'),
('led tv', 'electronics repair', 'en'),
('speaker repair', 'electronics repair', 'en'),
('amplifier', 'electronics repair', 'en'),
('mobile ka screen', 'mobile repair', 'ur'),
('phone toot gaya', 'mobile repair', 'ur'),

-- ═══════════════════════════════════════════════════════
-- HOME APPLIANCES
-- ═══════════════════════════════════════════════════════
('fridge not cooling', 'refrigerator repair', 'en'),
('refrigerator repair', 'appliance repair', 'en'),
('washing machine repair', 'appliance repair', 'en'),
('dryer repair', 'appliance repair', 'en'),
('microwave repair', 'appliance repair', 'en'),
('oven repair', 'appliance repair', 'en'),
('dishwasher', 'appliance repair', 'en'),
('water purifier', 'appliance repair', 'en'),
('ro repair', 'water purifier repair', 'en'),
('chimney cleaning', 'appliance repair', 'en'),
('vacuum cleaner', 'appliance repair', 'en'),
('iron repair', 'appliance repair', 'en'),
('mixer grinder', 'appliance repair', 'en'),
('ac not cooling', 'air conditioning', 'en'),
('ac gas refill', 'air conditioning', 'en'),
('ac installation', 'air conditioning', 'en'),
('ac service', 'air conditioning', 'en'),
('split ac', 'air conditioning', 'en'),
('window ac', 'air conditioning', 'en'),
('ac ka gas', 'air conditioning', 'ur'),

-- ═══════════════════════════════════════════════════════
-- AUTOMOTIVE
-- ═══════════════════════════════════════════════════════
('car service', 'auto mechanic', 'en'),
('oil change', 'auto mechanic', 'en'),
('brake repair', 'auto mechanic', 'en'),
('tire change', 'tire repair', 'en'),
('flat tire', 'tire repair', 'en'),
('tyre', 'tire repair', 'en'),
('battery dead', 'auto electrician', 'en'),
('car battery', 'auto electrician', 'en'),
('car paint', 'auto body repair', 'en'),
('car scratch', 'auto body repair', 'en'),
('windshield', 'auto glass', 'en'),
('car ac', 'auto ac repair', 'en'),
('engine repair', 'auto mechanic', 'en'),
('clutch repair', 'auto mechanic', 'en'),
('transmission', 'auto mechanic', 'en'),
('alignment', 'auto mechanic', 'en'),
('balancing', 'auto mechanic', 'en'),
('car polish', 'auto detailing', 'en'),
('ceramic coating', 'auto detailing', 'en'),
('bike repair', 'motorcycle mechanic', 'en'),
('motorcycle service', 'motorcycle mechanic', 'en'),
('tow truck', 'roadside assistance', 'en'),
('gaari ki marammat', 'auto mechanic', 'ur'),
('gaari dhulai', 'car wash', 'ur'),

-- ═══════════════════════════════════════════════════════
-- BEAUTY & PERSONAL CARE
-- ═══════════════════════════════════════════════════════
('facial', 'beauty salon', 'en'),
('manicure', 'nail salon', 'en'),
('pedicure', 'nail salon', 'en'),
('waxing', 'beauty salon', 'en'),
('threading', 'beauty salon', 'en'),
('hair color', 'hair salon', 'en'),
('hair dye', 'hair salon', 'en'),
('keratin', 'hair treatment', 'en'),
('straightening', 'hair treatment', 'en'),
('rebonding', 'hair treatment', 'en'),
('dandruff', 'hair treatment', 'en'),
('hair fall', 'hair treatment', 'en'),
('skin care', 'beauty salon', 'en'),
('acne treatment', 'dermatologist', 'en'),
('tattoo', 'tattoo artist', 'en'),
('piercing', 'body piercing', 'en'),
('spa', 'massage spa', 'en'),
('massage', 'massage spa', 'en'),
('body massage', 'massage spa', 'en'),
('bridal package', 'bridal makeup', 'en'),
('dulhan', 'bridal makeup', 'ur'),
('mehndi wali', 'henna artist', 'ur'),
('baal katna', 'barber', 'ur'),
('baal banwana', 'hair salon', 'ur'),

-- ═══════════════════════════════════════════════════════
-- FOOD & CATERING
-- ═══════════════════════════════════════════════════════
('pizza', 'restaurant', 'en'),
('burger', 'fast food', 'en'),
('cake', 'bakery', 'en'),
('pastry', 'bakery', 'en'),
('bread', 'bakery', 'en'),
('naan', 'bakery', 'ur'),
('tandoor', 'restaurant', 'ur'),
('biryani', 'restaurant', 'en'),
('nihari', 'restaurant', 'ur'),
('haleem', 'restaurant', 'ur'),
('chai', 'cafe', 'ur'),
('coffee', 'cafe', 'en'),
('ice cream', 'dessert shop', 'en'),
('mithai', 'sweet shop', 'ur'),
('shaadi ka khana', 'catering', 'ur'),
('party food', 'catering', 'en'),
('tiffin service', 'tiffin', 'en'),
('lunch box', 'tiffin', 'en'),
('home chef', 'home cooking', 'en'),
('cook at home', 'home cooking', 'en'),

-- ═══════════════════════════════════════════════════════
-- HEALTH & MEDICAL
-- ═══════════════════════════════════════════════════════
('fever', 'clinic', 'en'),
('cold and flu', 'clinic', 'en'),
('dentist', 'dental clinic', 'en'),
('toothache', 'dental clinic', 'en'),
('root canal', 'dental clinic', 'en'),
('braces', 'orthodontist', 'en'),
('eye doctor', 'ophthalmologist', 'en'),
('spectacles', 'optician', 'en'),
('glasses', 'optician', 'en'),
('contact lens', 'optician', 'en'),
('physiotherapy', 'physiotherapist', 'en'),
('x ray', 'diagnostic lab', 'en'),
('blood test', 'diagnostic lab', 'en'),
('ultrasound', 'diagnostic lab', 'en'),
('mri', 'diagnostic lab', 'en'),
('pharmacy', 'medical store', 'en'),
('medicine delivery', 'pharmacy', 'en'),
('ambulance', 'emergency services', 'en'),
('homeopathy', 'homeopathic clinic', 'en'),
('ayurveda', 'ayurvedic clinic', 'en'),
('unani', 'unani clinic', 'en'),
('dant ka doctor', 'dental clinic', 'ur'),
('aankh ka doctor', 'ophthalmologist', 'ur'),
('dawai', 'pharmacy', 'ur'),

-- ═══════════════════════════════════════════════════════
-- EDUCATION & TUTORING
-- ═══════════════════════════════════════════════════════
('math tutor', 'tutor', 'en'),
('science tutor', 'tutor', 'en'),
('english tutor', 'tutor', 'en'),
('home tuition', 'tutor', 'en'),
('online classes', 'tutor', 'en'),
('ielts', 'language training', 'en'),
('spoken english', 'language training', 'en'),
('computer class', 'computer training', 'en'),
('typing course', 'computer training', 'en'),
('driving school', 'driving instructor', 'en'),
('dance class', 'dance academy', 'en'),
('music class', 'music academy', 'en'),
('guitar lessons', 'music academy', 'en'),
('quran teacher', 'islamic education', 'en'),
('hafiz', 'islamic education', 'ur'),
('madrasa', 'islamic education', 'ur'),
('padhai', 'tutor', 'ur'),

-- ═══════════════════════════════════════════════════════
-- FASHION & CLOTHING
-- ═══════════════════════════════════════════════════════
('suit stitching', 'tailor', 'en'),
('blouse', 'tailor', 'en'),
('alteration', 'tailor', 'en'),
('hemming', 'tailor', 'en'),
('kurta', 'tailor', 'ur'),
('shalwar kameez', 'tailor', 'ur'),
('sherwani', 'men tailor', 'ur'),
('lehenga', 'bridal wear', 'ur'),
('saree', 'fashion designer', 'en'),
('embroidery', 'embroidery', 'en'),
('aari work', 'embroidery', 'ur'),
('hand work', 'embroidery', 'en'),
('dry cleaning', 'laundry', 'en'),
('stain removal', 'laundry', 'en'),
('ironing service', 'laundry', 'en'),
('kapde silwana', 'tailor', 'ur'),
('kapde dhulwana', 'laundry', 'ur'),

-- ═══════════════════════════════════════════════════════
-- CLEANING & HOME SERVICES
-- ═══════════════════════════════════════════════════════
('deep cleaning', 'home cleaning', 'en'),
('sofa cleaning', 'upholstery cleaning', 'en'),
('carpet cleaning', 'carpet cleaning', 'en'),
('bathroom cleaning', 'home cleaning', 'en'),
('kitchen cleaning', 'home cleaning', 'en'),
('water tank cleaning', 'tank cleaning', 'en'),
('cockroach', 'pest control', 'en'),
('rat control', 'pest control', 'en'),
('bed bugs', 'pest control', 'en'),
('mosquito', 'pest control', 'en'),
('deemak', 'termite control', 'ur'),
('khatmal', 'pest control', 'ur'),
('makdi', 'pest control', 'ur'),
('safai wala', 'home cleaning', 'ur'),
('jhaadu', 'home cleaning', 'ur'),

-- ═══════════════════════════════════════════════════════
-- EVENTS & CELEBRATIONS
-- ═══════════════════════════════════════════════════════
('birthday party', 'event planner', 'en'),
('wedding planner', 'event planner', 'en'),
('dj', 'dj services', 'en'),
('sound system', 'sound rental', 'en'),
('projector', 'av rental', 'en'),
('flower decoration', 'florist', 'en'),
('balloon decoration', 'event decoration', 'en'),
('stage decoration', 'event decoration', 'en'),
('photographer', 'photography', 'en'),
('videographer', 'videography', 'en'),
('drone photography', 'photography', 'en'),
('invitation card', 'printing', 'en'),
('gift wrapping', 'gift shop', 'en'),
('party hall', 'banquet hall', 'en'),
('marquee', 'banquet hall', 'en'),
('shaadi hall', 'banquet hall', 'ur'),
('mandap', 'event decoration', 'hi'),
('pandit', 'priest services', 'hi'),
('qawwali', 'entertainment', 'ur'),

-- ═══════════════════════════════════════════════════════
-- TRANSPORT & MOVING
-- ═══════════════════════════════════════════════════════
('packers and movers', 'movers and packers', 'en'),
('house shifting', 'movers and packers', 'en'),
('office shifting', 'movers and packers', 'en'),
('furniture moving', 'movers and packers', 'en'),
('truck rental', 'transport', 'en'),
('tempo', 'transport', 'en'),
('pickup van', 'transport', 'en'),
('courier', 'courier service', 'en'),
('parcel', 'courier service', 'en'),
('delivery service', 'courier service', 'en'),
('samaan bhejana', 'courier service', 'ur'),
('ghar shift', 'movers and packers', 'ur'),

-- ═══════════════════════════════════════════════════════
-- HOME IMPROVEMENT & INTERIOR
-- ═══════════════════════════════════════════════════════
('interior design', 'interior designer', 'en'),
('modular kitchen', 'kitchen design', 'en'),
('wardrobe', 'furniture', 'en'),
('false ceiling', 'interior designer', 'en'),
('pop design', 'ceiling work', 'en'),
('wallpaper', 'wall decor', 'en'),
('curtain', 'curtains', 'en'),
('blinds', 'window blinds', 'en'),
('sofa repair', 'upholstery', 'en'),
('furniture polish', 'furniture repair', 'en'),
('door repair', 'carpenter', 'en'),
('window repair', 'carpenter', 'en'),
('lock repair', 'locksmith', 'en'),
('duplicate key', 'locksmith', 'en'),
('chabi banana', 'locksmith', 'ur'),
('darwaza', 'carpenter', 'ur'),
('almari', 'furniture', 'ur'),
('palang', 'furniture', 'ur'),

-- ═══════════════════════════════════════════════════════
-- LEGAL & FINANCIAL
-- ═══════════════════════════════════════════════════════
('lawyer', 'legal services', 'en'),
('advocate', 'legal services', 'en'),
('property lawyer', 'legal services', 'en'),
('tax consultant', 'accounting', 'en'),
('ca', 'chartered accountant', 'en'),
('gst filing', 'accounting', 'en'),
('income tax', 'accounting', 'en'),
('insurance', 'insurance agent', 'en'),
('loan', 'financial services', 'en'),
('wakeel', 'legal services', 'ur'),
('munshi', 'legal services', 'ur'),

-- ═══════════════════════════════════════════════════════
-- PET SERVICES
-- ═══════════════════════════════════════════════════════
('dog training', 'pet training', 'en'),
('cat food', 'pet store', 'en'),
('dog food', 'pet store', 'en'),
('pet vaccination', 'veterinary', 'en'),
('fish tank', 'aquarium', 'en'),
('bird cage', 'pet store', 'en'),
('dog walker', 'pet care', 'en'),
('pet boarding', 'pet hostel', 'en'),
('janwar ka doctor', 'veterinary', 'ur'),
('kutta training', 'pet training', 'ur'),

-- ═══════════════════════════════════════════════════════
-- TRAVEL & TOURISM
-- ═══════════════════════════════════════════════════════
('flight booking', 'travel agency', 'en'),
('hotel booking', 'travel agency', 'en'),
('passport', 'travel agency', 'en'),
('visa consultant', 'visa services', 'en'),
('tour package', 'travel agency', 'en'),
('honeymoon', 'travel agency', 'en'),
('rent a car', 'car rental', 'en'),
('taxi', 'cab service', 'en'),
('cab', 'cab service', 'en'),
('bus booking', 'transport', 'en'),
('umrah package', 'travel agency', 'ur'),
('ziyarat', 'travel agency', 'ur'),

-- ═══════════════════════════════════════════════════════
-- AGRICULTURE & GARDENING
-- ═══════════════════════════════════════════════════════
('gardener', 'gardening', 'en'),
('lawn mowing', 'gardening', 'en'),
('plant nursery', 'nursery', 'en'),
('fertilizer', 'gardening supplies', 'en'),
('pesticide', 'gardening supplies', 'en'),
('tree cutting', 'tree service', 'en'),
('landscaping', 'landscaping', 'en'),
('mali', 'gardener', 'ur'),
('paudha', 'nursery', 'ur'),

-- ═══════════════════════════════════════════════════════
-- PRINTING & SIGNAGE
-- ═══════════════════════════════════════════════════════
('business card', 'printing', 'en'),
('brochure', 'printing', 'en'),
('pamphlet', 'printing', 'en'),
('sticker printing', 'printing', 'en'),
('t-shirt printing', 'printing', 'en'),
('mug printing', 'printing', 'en'),
('neon sign', 'signage', 'en'),
('led board', 'signage', 'en'),
('shop board', 'signage', 'en'),
('name plate', 'signage', 'en'),

-- ═══════════════════════════════════════════════════════
-- GROCERY & DAILY NEEDS
-- ═══════════════════════════════════════════════════════
('atta', 'grocery', 'ur'),
('chawal', 'grocery', 'ur'),
('daal', 'grocery', 'ur'),
('sabzi', 'vegetable market', 'ur'),
('doodh', 'dairy', 'ur'),
('phal', 'fruit market', 'ur'),
('meat shop', 'butcher', 'en'),
('qasai', 'butcher', 'ur'),
('chicken shop', 'poultry', 'en'),
('murgi', 'poultry', 'ur'),
('fish market', 'seafood', 'en'),
('machli', 'seafood', 'ur'),
('organic food', 'organic store', 'en'),
('mineral water', 'water delivery', 'en'),

-- ═══════════════════════════════════════════════════════
-- REAL ESTATE
-- ═══════════════════════════════════════════════════════
('flat for rent', 'real estate', 'en'),
('house for sale', 'real estate', 'en'),
('plot for sale', 'real estate', 'en'),
('property dealer', 'real estate agent', 'en'),
('broker', 'real estate agent', 'en'),
('pg accommodation', 'rental', 'en'),
('hostel', 'accommodation', 'en'),
('warehouse', 'commercial property', 'en'),
('shop for rent', 'commercial property', 'en'),
('zameen', 'real estate', 'ur'),
('kiraya', 'rental', 'ur'),
('makan', 'real estate', 'ur'),

-- ═══════════════════════════════════════════════════════
-- SPORTS & FITNESS
-- ═══════════════════════════════════════════════════════
('personal trainer', 'fitness', 'en'),
('zumba', 'fitness', 'en'),
('swimming pool', 'swimming', 'en'),
('badminton court', 'sports', 'en'),
('cricket coaching', 'sports coaching', 'en'),
('football', 'sports', 'en'),
('boxing', 'martial arts', 'en'),
('karate', 'martial arts', 'en'),
('sports equipment', 'sports store', 'en'),

-- ═══════════════════════════════════════════════════════
-- ADDITIONAL MISSPELLINGS & VARIANTS
-- ═══════════════════════════════════════════════════════
('aircondition', 'air conditioning', 'en'),
('airconditioning', 'air conditioning', 'en'),
('ac repare', 'air conditioning', 'en'),
('refridgerator', 'refrigerator repair', 'en'),
('refrigerater', 'refrigerator repair', 'en'),
('washingmachine', 'washing machine repair', 'en'),
('electritian', 'electrician', 'en'),
('electrican', 'electrician', 'en'),
('plumbr', 'plumber', 'en'),
('plumbar', 'plumber', 'en'),
('carpeter', 'carpenter', 'en'),
('carpentar', 'carpenter', 'en'),
('machanic', 'mechanic', 'en'),
('mekanik', 'mechanic', 'en'),
('sallon', 'salon', 'en'),
('parler', 'parlour', 'en'),
('restorant', 'restaurant', 'en'),
('restourant', 'restaurant', 'en'),
('fotografy', 'photography', 'en'),
('photgraphy', 'photography', 'en'),
('photgrapher', 'photographer', 'en'),
('cleanng', 'cleaning', 'en'),
('clening', 'cleaning', 'en'),
('interier', 'interior designer', 'en'),
('furnicher', 'furniture', 'en'),
('furnitur', 'furniture', 'en'),
('plumbing', 'plumber', 'en'),
('electrical', 'electrician', 'en'),
('carpentry', 'carpenter', 'en'),
('painting', 'painter', 'en'),
('welding', 'welder', 'en'),
('fabrication', 'metal fabrication', 'en'),
('aluminium work', 'aluminum fabrication', 'en'),
('iron gate', 'iron works', 'en'),
('grill work', 'iron works', 'en'),
('railing', 'iron works', 'en'),
('lohe ka kaam', 'iron works', 'ur'),
('welding wala', 'welder', 'ur')

ON CONFLICT DO NOTHING;
